# src/ion/Steps/__init__.py
import os
import json
import asyncio


async def extract_summary_info(config):
    await asyncio.sleep(0.05)


async def generate_rag_diagnosis(config):
    await asyncio.sleep(0.05)


async def intra_module_merge(config):
    await asyncio.sleep(0.05)


async def inter_module_merge(config):
    # Return something that format_diagnosis_md can serialize
    await asyncio.sleep(0.05)
    return {
        "diagnosis": "This is a placeholder diagnosis generated by the dev stub.",
        "sources": {
            "1": {"file": "header.txt", "text": "Example source text"}
        }
    }


async def format_diagnosis_md(config, final_diagnosis):
    # Write Output/final_diagnosis/final_diagnosis.json (what your API expects)
    out_dir = os.path.join(config["analysis_root"], "final_diagnosis")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "final_diagnosis.json"), "w") as f:
        json.dump(final_diagnosis, f)
    return final_diagnosis
